.row-content-block.build-content.middle-block
  .pull-right
    - if can?(current_user, :update_pipeline, @project)
      - if ci_commit.builds.latest.failed.any?(&:retryable?)
        = link_to "重试失败", retry_namespace_project_pipeline_path(@project.namespace, @project, ci_commit.id), class: 'btn btn-grouped btn-primary', method: :post

      - if ci_commit.builds.running_or_pending.any?
        = link_to "取消运行", cancel_namespace_project_pipeline_path(@project.namespace, @project, ci_commit.id), data: { confirm: '确定要继续么？' }, class: 'btn btn-grouped btn-danger', method: :post

  .oneline.clearfix
    - if defined?(pipeline_details) && pipeline_details
      管道
      = link_to "##{ci_commit.id}", namespace_project_pipeline_path(@project.namespace, @project, ci_commit.id), class: "monospace"
      ：
      - if ci_commit.ref
        = link_to ci_commit.ref, namespace_project_commits_path(@project.namespace, @project, ci_commit.ref), class: "monospace"
        的
      - if defined?(link_to_commit) && link_to_commit
        = link_to ci_commit.short_sha, namespace_project_commit_path(@project.namespace, @project, ci_commit.sha), class: "monospace"
        提交的
      = pluralize ci_commit.statuses.count(:id), "次构建", "次构建"
      - if ci_commit.duration
        耗费
        = time_interval_in_words ci_commit.duration

- if ci_commit.yaml_errors.present?
  .bs-callout.bs-callout-danger
    %h4 在 .gitlab-ci.yml 中发现错误：
    %ul
      - ci_commit.yaml_errors.split(",").each do |error|
        %li= error
    你也可以使用 #{link_to "Lint", ci_lint_path} 工具测试你的 .gitlab-ci.yml 文件

- if @project.builds_enabled? && !ci_commit.ci_yaml_file
  .bs-callout.bs-callout-warning
    此提交里面没有发现 .gitlab-ci.yml 文件

.table-holder
  %table.table.builds
    - ci_commit.statuses.stages.each do |stage|
      = render 'projects/commit/ci_stage', stage: stage, statuses: ci_commit.statuses.where(stage: stage)
